version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: papafila123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

  studio:
    image: supabase/studio
    ports:
      - "3001:3000"
    depends_on:
      - db

volumes:
  supabase_data: